### PR TITLE
Parameterize OAuth credentials and URLs

### PR DESCRIPTION
**Pull request by laitn**
This PR parameterizes Cloud Print URLs in case developer needs to access testing oauth server or testing local GCP servers.

The old command still works with production URLs by default:

gcp-connector-util init

Then in order to connect to testing server, you need following command:

gcp-connector-util init --gcp-oauth-client-id="<TEST CLIENT ID>" --gcp-oauth-client-secret="<TEST CLIENT SECRET>" --gcp-oauth-auth-url="<OAUTH AUTH URL>" --gcp-oauth-token-url="<OAUTH TOKEN URL>" --gcp-oauth-device-code-url="<DEVICE CODE URL>" --gcp-base-url="<GCP API BASE URL>" --gcp-oauth-token-poll-url="<OAUTH TOKEN POLL URL>"

### CODE REVIEW

**Review by adlr — COMMENTED** [review]
I don't have any issues here. About the commit message itself, tho: The first line of the commit message should be a short one-line description. Then you can have a paragraph below with more details. It looks like it just split one paragraph into the first/subsequent lines.

Also, I wonder if we can publish servers for testing? Maybe not.

**Comment by laitn** [comment]
I'm not sure if testing servers are accessible outside. I will send a doc later detailing testing instructions.

**Comment by adlr** [comment]
Just one nit, but otherwise looks good. It looks like in the commit description you're using "CL" and "PR" for the same thing. Also, it's a bit redundant to say "this CL" b/c of course the description is for this CL. Maybe change the first line to:

Parameterize OAuth credentials and URLs

?

I would appreciate if someone else would review as well, but if nobody wants to, I'm find to check-in w/ that one change.

Thanks!

**Review by agoode — APPROVED** [review]

**Comment by laitn** [comment]
thanks!

**Comment by adjobscc-del** [comment]
30b5178b0100f95480e9854a09458fb2b22cea3a

**Pull request merged**
